# Generated by Django 2.1.2 on 2018-10-08 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_auto_20181008_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='posteado',
        ),
    ]
