# Generated by Django 2.1.2 on 2018-10-08 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_remove_post_posteado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idUsu',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
